# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-15 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20190615_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
